<?php
/**
 * Generated by CitOmni Maintenance service.
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * Generated at (local): 2025-09-25T22:41:01+02:00
 * Generated at (UTC)  : 2025-09-25T20:41:01+00:00
 *
 * This file is intentionally side-effect free:
 * It must only return a plain array consumed by the runtime.
 */

return array (
  'enabled' => false,
  'allowed_ips' => 
  array (
  ),
  'retry_after' => 300,
);
